name: Fetch Chiki RSS

on:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごと
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch RSS
        run: |
          curl -s "https://feeds.tbs.co.jp/rss/tbsradio/TS954.xml?limit=100" -o rss/chiki.xml

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rss/chiki.xml
          git commit -m "Update Chiki RSS"
          git push
